---
name: Checks
on: [push]
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: pip install flake8
      - name: Lint
        run: flake8 .
